# Generated by Django 2.2.8 on 2020-01-04 11:52

import django.core.validators
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='InvitedUser',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('mobile', models.CharField(error_messages={'unique': 'This mobile number is already invited'}, max_length=10, unique=True, validators=[django.core.validators.RegexValidator(message='Phone number must be 10 digit', regex='^\\+?1?\\d{10,10}$')])),
            ],
            options={
                'ordering': ['-created_at'],
                'verbose_name_plural': 'InvitedUsers',
            },
        ),
    ]
