# Generated by Django 2.2.8 on 2019-12-22 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('company', models.CharField(max_length=64)),
                ('description', models.CharField(max_length=128)),
            ],
            options={
                'verbose_name_plural': 'Games',
                'ordering': ['name'],
            },
        ),
    ]
